### ISSUE TITLE
When generating binary fixation mask, should I follow the way demo.m file uses?

### ISSUE THREAD

**Issue by kylemin** [remega/LEDOV-eye-tracking-database#5]
demo.m filters out the fixation points outside the center mask (height/20). Also, it filters out the points where the normalized intensity is below 0.4.
Should I follow the above two filtering if I want to do an experiment in your setting?

**Comment by remega** [comment]
Actually, we only filtered the center fixation points at the beginning of the video, since our eye-tracking experiments guided the subjects to see center when videos changed. As for threshold of 0.4，it is only used for visualization. You can try to change it for generating heat maps. When generating the ground-truth fixation maps, we do not filter the maps by intensity.

**Comment by kylemin** [comment]
Thanks for your comment.
